  variable "tag_environment" {}
  variable "tag_owner" {}
  variable "tag_cost_code" {}
  variable "vpc_id" {}
  variable "subnet_id" {}
  variable "nuget_api_key" {}
  variable "packagesPath" {}
  variable "nuget_instance_type" {}
  variable "nuget_server_keypair" {}